# Identificador único del proyecto en SonarQube
sonar.projectKey=taller-sast-monorepo
sonar.projectName=Taller SAST Monorepo
sonar.projectVersion=1.0

# Rutas de los archivos fuentes que se van a analizar (dentro de apps)
sonar.sources=apps

# Exclusiones para evitar escanear dependencias y compilaciones
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/*.spec.ts, **/*.spec.js, cmbonifaz/**

# Codificación de los archivos fuente
sonar.sourceEncoding=UTF-8
